name: amik_learn
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.0.2
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3

flutter:
  assets:
    - assets/images/
  fonts:  
  - family: PlusJakartaSans
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
      - asset: assets/fonts/PlusJakartaSans-Bold.ttf
      - asset: assets/fonts/PlusJakartaSans-Light.ttf
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
